---
version: "2.1"

volumes:
  automation_postgres:

services:
  temp-service_postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: THDB
      POSTGRES_PASSWORD: test-project
      POSTGRES_USER: test-project
    ports:
      - 5432:5432

  temp-service:
    image: temp-service:latest
    build: .
    ports:
      - 8080:8080
    depends_on:
      - temp-service_postgres